apiVersion: v1
kind: Pod
metadata:
  name: lables
  namespace: roboshop
  labels:
    project: roboshop
    componenet: frontend
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
