apiVersion: v1
kind: Pod
metadata:
   name: resource-demo
spec:
  containers:
    - name: nginx
      image: nginx
  resources:
   requests:
     memoery: "64Mi"
     cpu: "100m"
   limits:
    memory: "128Mi"
    cpu: "150m"